import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import { writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const test = process.argv[2] === "test";
const mainPath = "main.js";

// Create a safe setImmediate shim that uses setTimeout instead of dynamic script injection.
// Polyfill packages (setimmediate, immediate, lie) use createElement("script") as a
// fallback for async scheduling, which triggers Obsidian's "dynamic script element creation"
// security check. In Electron 32+ (Obsidian 1.13+), native APIs are available.
const shimDir = join(__dirname, "node_modules", ".esbuild-shims");
mkdirSync(shimDir, { recursive: true });
writeFileSync(
	join(shimDir, "setimmediate.js"),
	`(function(global) {
	if (typeof global.setImmediate === "function") return;
	global.setImmediate = function(fn) {
		var args = Array.prototype.slice.call(arguments, 1);
		return setTimeout(function() { fn.apply(null, args); }, 0);
	};
	global.clearImmediate = function(id) { clearTimeout(id); };
})(typeof globalThis !== "undefined" ? globalThis : typeof self !== "undefined" ? self : this);
module.exports = global.setImmediate;\n`,
);
writeFileSync(
	join(shimDir, "immediate.js"),
	`var setImmediate = typeof globalThis !== "undefined" && globalThis.setImmediate
	? globalThis.setImmediate
	: function(fn) { return setTimeout(fn, 0); };
var clearImmediate = typeof globalThis !== "undefined" && globalThis.clearImmediate
	? globalThis.clearImmediate
	: function(id) { clearTimeout(id); };
module.exports = setImmediate;
module.exports.clearImmediate = clearImmediate;\n`,
);
writeFileSync(
	join(shimDir, "lie.js"),
	`module.exports = Promise;\n`,
);
// Bluebird-compatible subset for mammoth. Bluebird builds method callers with
// new Function() — the last dynamic code generation left in the bundle after the bot
// client migration (0.6). mammoth's lib/promises.js needs only the pieces below
// (verified against its source: resolve/all/props/reject/promisify/mapSeries/attempt,
// instance .caught/.tap/.done, and `new bluebird.Promise`). The statics are wrapped
// functions, not extracted references, because mammoth detaches them from the class.
writeFileSync(
	join(shimDir, "bluebird-promise.js"),
	`"use strict";
module.exports = function () {
	class BluebirdShim extends Promise {}
	const P = BluebirdShim;
	P.Promise = P;
	P.prototype.caught = P.prototype.catch;
	P.prototype.tap = function (fn) {
		return this.then(function (value) { return P.resolve(fn(value)).then(function () { return value; }); });
	};
	P.prototype.done = function (onFulfilled, onRejected) {
		this.then(onFulfilled, onRejected).catch(function (e) {
			setTimeout(function () { throw e; }, 0);
		});
	};
	P.resolve = function (v) { return Promise.resolve.call(P, v); };
	P.reject = function (e) { return Promise.reject.call(P, e); };
	P.all = function (arr) { return Promise.all.call(P, arr); };
	P.props = function (obj) {
		const keys = Object.keys(obj);
		return P.all(keys.map(function (k) { return obj[k]; })).then(function (vals) {
			const out = {};
			keys.forEach(function (k, i) { out[k] = vals[i]; });
			return out;
		});
	};
	P.attempt = function (fn) { return P.resolve().then(function () { return fn(); }); };
	P.promisify = function (fn) {
		return function (...args) {
			const self = this;
			return new P(function (res, rej) {
				fn.call(self, ...args, function (err, val) { if (err) rej(err); else res(val); });
			});
		};
	};
	P.mapSeries = function (input, mapper) {
		return P.resolve(input).then(function (arr) {
			let chain = P.resolve([]);
			for (const item of arr) {
				chain = chain.then(function (acc) {
					return P.resolve(item)
						.then(mapper)
						.then(function (mapped) { acc.push(mapped); return acc; });
				});
			}
			return chain;
		});
	};
	return P;
};\n`,
);

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	alias: {
		setimmediate: join(shimDir, "setimmediate.js"),
		immediate: join(shimDir, "immediate.js"),
		lie: join(shimDir, "lie.js"),
	},
	plugins: [
		{
			name: "bluebird-shim",
			setup(build) {
				// mammoth reaches bluebird through the deep path "bluebird/js/release/promise";
				// the whole package (and its new Function code generation) is replaced by the
				// shim. Not an `alias` entry: esbuild matches alias keys by package name and
				// appends the subpath to the target, producing ".../bluebird-promise.js/js/release/promise".
				build.onResolve({ filter: /^bluebird(\/.*)?$/ }, () => ({
					path: join(shimDir, "bluebird-promise.js"),
				}));
			},
		},
		{
			name: "pdf-worker-embed",
			setup(build) {
				// pdf.js runs its worker on the main thread when globalThis.pdfjsWorker is set, and
				// the worker module sets it on import. A plugin ships main.js alone, so there is no
				// separate worker file to point workerSrc at — the worker is bundled and imported
				// lazily by documentExtractor. Resolved by path: pdf-parse's package exports do not
				// expose it, and this copy matches the pdf.js version pdf-parse bundles.
				build.onResolve({ filter: /^virtual:pdf-worker$/ }, () => ({
					path: join(__dirname, "node_modules", "pdf-parse", "dist", "worker", "pdf.worker.mjs"),
				}));
			},
		},
		{
			name: "strip-script-injection",
			setup(build) {
				// Replace inline setImmediate polyfills that use createElement("script")
				// with safe setTimeout-based alternatives. Targets jszip's embedded copy.
				//
				// Scoped to jszip on purpose: rewriting every node_modules file that mentions
				// createElement("script") would silently break any dependency that creates
				// script elements legitimately, and the breakage would only surface at runtime.
				build.onLoad({ filter: /[\\/]node_modules[\\/]jszip[\\/].*\.m?js$/ }, async (args) => {
					const { readFile } = await import("fs/promises");
					let contents = await readFile(args.path, "utf8");
					// Only files that actually construct a script element are candidates.
					const createsScriptElement = /\.createElement\(\s*["']script["']\s*\)/;
					if (!createsScriptElement.test(contents)) return null;
					const original = contents;
					// Replace the script-injection setImmediate pattern with setTimeout
					contents = contents.replace(
						/["']onreadystatechange["']\s*in\s+\w+(?:\.document)?\.createElement\(["']script["']\)/g,
						"false",
					);
					contents = contents.replace(/\w+(?:\.document)?\.createElement\(["']script["']\)/g, "undefined");
					// Fail the build rather than shipping the injection. The patterns above are
					// pinned to jszip's current shape; an upgrade that renames the receiver would
					// otherwise slip a createElement("script") into main.js, and Obsidian's plugin
					// review rejects that — a failure here is far cheaper to notice than there.
					if (contents === original) {
						throw new Error(
							`strip-script-injection: ${args.path} creates a script element but matched no known ` +
								`pattern. Inspect the file and update the replacements in esbuild.config.mjs.`,
						);
					}
					// jszip's embedded setImmediate also compiles string callbacks with
					// new Function("" + fn) — a branch nothing reaches (the plugin never passes
					// strings) that still reads as dynamic code generation to a reviewer.
					// A string callback now throws instead of being compiled.
					contents = contents.replace(
						/new Function\(\s*(['"])\1\s*\+\s*(\w+)\s*\)/g,
						'(function(){ throw new TypeError("string callbacks are not supported"); })',
					);
					return { contents, loader: "js" };
				});

				// pdf-parse carries three pieces of Function-constructor code: pdf.js's
				// eval-support probe (`new Function("")`), a webpack-runtime global
				// detection (`Function("return this")()`), and core-js's dynamic-require
				// fallback (`Function('return require("'+name+'")')()`). None is needed:
				// the probe is pinned to false (the no-eval path is what mobile gets
				// anyway), the global is globalThis, and a dynamic require must fail into
				// its surrounding try/catch rather than be compiled.
				build.onLoad({ filter: /[\\/]node_modules[\\/]pdf-parse[\\/].*\.(m?js|cjs)$/ }, async (args) => {
					const { readFile } = await import("fs/promises");
					const contents = await readFile(args.path, "utf8");
					if (!/new Function|[^.\w$]Function\s*\(\s*['"]/.test(contents)) return null;
					// Probe patterns for both shipped shapes: readable
					// (`try { new Function(""); return true; } catch { return false; }`) and
					// minified (`try{return new Function(""),!0}catch{return!1}`).
					const probe =
						// `return\s*` in the second shape: the minified worker writes `return!0`.
						/try\s*\{\s*(?:return\s+new Function\(""\)\s*,\s*(?:!0|true)|new Function\(""\);\s*return\s*(?:!0|true);?)\s*\}\s*catch\s*(?:\(\w*\)\s*)?\{\s*return\s*(?:!1|false);?\s*\}/g;
					const replaced = contents
						.replace(probe, "return false;")
						.replace(/Function\((['"])return this\1\)\(\)/g, "globalThis")
						.replace(
							/Function\('return require\("'\s*\+\s*\w+\s*\+\s*'"\)'\)\(\)/g,
							'(function(){ throw new Error("dynamic require is disabled in this bundle"); })()',
						)
						// The embedded worker (pdf.worker.mjs) compiles PostScript functions with
						// new Function behind `isEvalSupported`, which the probe above pins to
						// false. Returning null takes pdf.js's own interpreter path instead.
						.replace(/new Function\("src","srcOffset","dest","destOffset",\w+\)/g, "null");
					// Quote-anchored on purpose: it matches real Function-constructor calls
					// (their first argument is a string) without tripping on prose in comments.
					if (/new Function|[^.\w$]Function\s*\(\s*['"]/.test(replaced)) {
						throw new Error(
							`strip-script-injection: ${args.path} still contains Function-constructor code ` +
								`after the known patterns were applied. Update the patterns in esbuild.config.mjs.`,
						);
					}
					return { contents: replaced, loader: "js" };
				});

				// underscore (a mammoth dependency) compiles _.template with new Function at
				// call time, and detects the global root with Function('return this')().
				// Nothing in the bundle calls _.template — mammoth uses extend/map and
				// friends — so the compile throws instead, and the root is globalThis.
				build.onLoad({ filter: /[\\/]node_modules[\\/]underscore[\\/].*\.c?js$/ }, async (args) => {
					const { readFile } = await import("fs/promises");
					const contents = await readFile(args.path, "utf8");
					if (!/new Function|[^.\w$]Function\s*\(\s*['"]/.test(contents)) return null;
					const replaced = contents
						.replace(
							/new Function\(([^;]*?)\)/g,
							'(function(){ throw new Error("_.template is disabled in this bundle"); })()',
						)
						.replace(/Function\((['"])return this\1\)\(\)/g, "globalThis");
					// Quote-anchored on purpose: it matches real Function-constructor calls
					// (their first argument is a string) without tripping on prose in comments.
					if (/new Function|[^.\w$]Function\s*\(\s*['"]/.test(replaced)) {
						throw new Error(
							`strip-script-injection: ${args.path} still contains Function-constructor code ` +
								`after the known patterns were applied. Update the patterns in esbuild.config.mjs.`,
						);
					}
					return { contents: replaced, loader: "js" };
				});
			},
		},
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod,
	// src/utils/queues.ts keys its serialization queues by Function.prototype.name.
	// Minified names would make those keys meaningless.
	keepNames: true,
	outfile: mainPath,
});

if (prod || test) {
	await context.rebuild();

	// v0.4 performance budget: the production bundle must not silently grow. Measured at
	// 2.38 MB after the 0.6 bot-client migration removed node-telegram-bot-api and its
	// request/bluebird chain (was 3.06 MB); the remaining weight is GramJS, bundled but
	// desktop-only at runtime (see telegram/user/userGateway.ts). The ceiling catches
	// accidental regressions — a new heavyweight dependency, an import that defeats tree
	// shaking.
	const { statSync, readFileSync: readBundle } = await import("fs");
	// Raised 3.0 → 3.5 MB (2026-09-14): the pdf.js worker (~1 MB) is now embedded so PDF text
	// extraction works inside Obsidian at all. It is imported lazily, so onload is unaffected.
	const BUNDLE_BUDGET_BYTES = 3.5 * 1024 * 1024;

	// v0.6 review invariant: no dynamic code generation ships, at all. The shims above
	// remove every known source; this assertion is what keeps the claim true when a
	// dependency update introduces a new one. (`[^.\w$]Function\s*\(` matches bare
	// Function-constructor calls without matching `x.Function(` member calls.)
	if (prod) {
		const bundle = readBundle(mainPath, "utf8");
		const dynamicCode = [
			[/[^.\w$]eval\s*\(/g, "eval("],
			[/new Function/g, "new Function"],
			[/[^.\w$]Function\s*\(/g, "bare Function("],
			[/createElement\(\s*["']script["']\s*\)/g, 'createElement("script")'],
		]
			.map(([re, label]) => ({ label, count: (bundle.match(re) || []).length }))
			.filter(({ count }) => count > 0);
		if (dynamicCode.length > 0) {
			console.error(
				`Dynamic code generation found in main.js: ` +
					dynamicCode.map(({ label, count }) => `${count}× ${label}`).join(", ") +
					`. A dependency changed — extend the strip-script-injection patterns in esbuild.config.mjs.`,
			);
			process.exit(1);
		}
	}

	const sizeBytes = statSync(mainPath).size;
	const asMB = (bytes) => (bytes / (1024 * 1024)).toFixed(2);
	console.log(`main.js: ${asMB(sizeBytes)} MB (budget ${asMB(BUNDLE_BUDGET_BYTES)} MB)`);
	if (prod && sizeBytes > BUNDLE_BUDGET_BYTES) {
		console.error(
			`Bundle size budget exceeded: main.js is ${asMB(sizeBytes)} MB, budget is ${asMB(BUNDLE_BUDGET_BYTES)} MB. ` +
				`Check what got bundled (npx esbuild --analyze) before raising the budget.`,
		);
		process.exit(1);
	}
	process.exit(0);
} else {
	await context.watch();
}
