import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "module";
import { writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const test = process.argv[2] === "test";
const mainPath = "main.js";

// Create a safe setImmediate shim that uses setTimeout instead of dynamic script injection.
// Polyfill packages (setimmediate, immediate, lie) use createElement("script") as a
// fallback for async scheduling, which triggers Obsidian's "dynamic script element creation"
// security check. In Electron 32+ (Obsidian 1.13+), native APIs are available.
const shimDir = join(__dirname, "node_modules", ".esbuild-shims");
mkdirSync(shimDir, { recursive: true });
writeFileSync(
	join(shimDir, "setimmediate.js"),
	`(function(global) {
	if (typeof global.setImmediate === "function") return;
	global.setImmediate = function(fn) {
		var args = Array.prototype.slice.call(arguments, 1);
		return setTimeout(function() { fn.apply(null, args); }, 0);
	};
	global.clearImmediate = function(id) { clearTimeout(id); };
})(typeof globalThis !== "undefined" ? globalThis : typeof self !== "undefined" ? self : this);
module.exports = global.setImmediate;\n`,
);
writeFileSync(
	join(shimDir, "immediate.js"),
	`var setImmediate = typeof globalThis !== "undefined" && globalThis.setImmediate
	? globalThis.setImmediate
	: function(fn) { return setTimeout(fn, 0); };
var clearImmediate = typeof globalThis !== "undefined" && globalThis.clearImmediate
	? globalThis.clearImmediate
	: function(id) { clearTimeout(id); };
module.exports = setImmediate;
module.exports.clearImmediate = clearImmediate;\n`,
);
writeFileSync(
	join(shimDir, "bluebird.js"),
	`module.exports = Promise;
module.exports.Promise = Promise;
module.exports.resolve = Promise.resolve.bind(Promise);
module.exports.reject = Promise.reject.bind(Promise);
module.exports.all = Promise.all.bind(Promise);
module.exports.race = Promise.race.bind(Promise);
module.exports.method = function(fn) { return function() { try { return Promise.resolve(fn.apply(this, arguments)); } catch(e) { return Promise.reject(e); } }; };
module.exports.try = function(fn) { return Promise.resolve().then(fn); };
module.exports.map = function(arr, fn) { return Promise.all(arr.map(fn)); };
module.exports.each = function(arr, fn) { return arr.reduce(function(p, v, i) { return p.then(function() { return fn(v, i, arr.length); }); }, Promise.resolve()); };
module.exports.props = function(obj) { var keys = Object.keys(obj); return Promise.all(keys.map(function(k) { return obj[k]; })).then(function(vals) { var r = {}; keys.forEach(function(k, i) { r[k] = vals[i]; }); return r; }); };
module.exports.coroutine = function(fn) { return function() { return Promise.resolve(fn.apply(this, arguments)); }; };
module.exports.promisify = function(fn) { return function() { var args = Array.prototype.slice.call(arguments); return new Promise(function(resolve, reject) { args.push(function(err, result) { if (err) reject(err); else resolve(result); }); fn.apply(null, args); }); }; };
module.exports.promisifyAll = function(obj) { var result = {}; Object.keys(obj).forEach(function(key) { if (typeof obj[key] === 'function') { result[key + 'Async'] = module.exports.promisify(obj[key]); } result[key] = obj[key]; }); return result; };
module.exports.delay = function(ms) { return new Promise(function(resolve) { setTimeout(resolve, ms); }); };
\n`,
);
writeFileSync(
	join(shimDir, "lie.js"),
	`module.exports = Promise;\n`,
);

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	alias: {
		setimmediate: join(shimDir, "setimmediate.js"),
		immediate: join(shimDir, "immediate.js"),
		lie: join(shimDir, "lie.js"),
	},
	plugins: [
		{
			name: "bluebird-shim",
			setup(build) {
				// Redirect all bluebird imports (including sub-paths like bluebird/js/release/promise)
				build.onResolve({ filter: /^bluebird/ }, () => ({
					path: join(shimDir, "bluebird.js"),
				}));
			},
		},
		{
			name: "strip-script-injection",
			setup(build) {
				// Replace inline setImmediate polyfills that use createElement("script")
				// with safe setTimeout-based alternatives. Targets jszip's embedded copy.
				build.onLoad({ filter: /\.m?js$/ }, async (args) => {
					// Only process files from node_modules that might contain the pattern
					if (!args.path.includes("node_modules")) return null;
					const { readFile } = await import("fs/promises");
					let contents = await readFile(args.path, "utf8");
					// Fast check: skip if no script injection pattern present
					if (!contents.includes('createElement') || !contents.includes('script')) return null;
					const original = contents;
					// Replace the script-injection setImmediate pattern with setTimeout
					contents = contents.replace(
						/["']onreadystatechange["']\s*in\s+\w+(?:\.document)?\.createElement\(["']script["']\)/g,
						"false",
					);
					contents = contents.replace(
						/\w+(?:\.document)?\.createElement\(["']script["']\)/g,
						"undefined",
					);
					if (contents === original) return null;
					return { contents, loader: "js" };
				});
			},
		},
	],
	format: "cjs",
	target: "es2020",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod,
	outfile: mainPath,
});

if (prod || test) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
